services:
  app:
    build: ./app
    ports:
      - "7777:80"
    volumes:
      - ./app:/var/www/app  # live reload frontend

  php:
    build: ./server
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - ./server:/var/www/server  # live reload backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: --sql-mode=""
    ports:
      - "9999:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./server/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  