services:
  app:
    build: ./app
    ports:
      - "7777:80"

  php:
    build: ./server
    ports:
      - "8888:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --sql-mode=""
    ports:
      - "9999:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./server/sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
