server {
    listen 80;
    root /var/www/app;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    error_page 404 /html/404.html;

    location = /html/404.html {
        internal;
    }
}